on:
    push:
      branches:
        - feature/*

permissions:
    contents: write
    pull-requests: write

name: Pre Release

jobs:
    release-new-version:
        runs-on: ubuntu-latest
        steps:
        - uses: google-github-actions/release-please-action@v3
          with:
            command: manifest
            prerelease: true
            release-as: 1.0.2-alpha
            release-type: simple
            extra-files: |
              README.md
              FibriCheckCameraSDK.podspec